language: php
php: '7.1'

cache:
  directories:
    - $HOME/.cache/composer

jobs:
  include:
    - stage: codestyle-check
      before_script:
        - composer global require friendsofphp/php-cs-fixer
      script:
        - $HOME/.config/composer/vendor/bin/php-cs-fixer --diff --dry-run --verbose fix ./src

    - stage: tests
      before_script:
        - composer install --no-interaction
      script:
        - vendor/bin/phpunit --coverage-text --colors=never
      after_success:
        - bash <(curl -s https://codecov.io/bash)
