services:
    VisualCraft\ApiDeserializerBundle\ApiDeserializerBuilderFactory:
        class: VisualCraft\ApiDeserializerBundle\ApiDeserializerBuilderFactory
        arguments:
            - "@serializer"
            - "@validator"
