services:
    VisualCraft\DeserializerBundle\DeserializerBuilderFactory:
        class: VisualCraft\DeserializerBundle\DeserializerBuilderFactory
        arguments:
            - "@serializer"
            - "@validator"
